---
{title: "Linea de comandos", subtitle: "POSIX en Windows" ,
date: '2020-11-26',
author: "Alejandro Acevedo-Aracena, _PhD_^[_FONDECYT Postdoctoral Fellow_, Universidad de Chile, deepen.data@gmail.com]; Manuel Muñoz-González^[_Pregrado_, Universidad de Chile]", output: {html_document: {theme: flatly, highlight: tango, toc: true, toc_float: {collapsed: false, smooth_scroll: true}, df_print: paged, code_folding: show}, html_notebook: default}}
---

# Terminal, shells, y niveles de abstracción

Muchos programas de bioinformatica no poseen una interfaz grafica, solo usando la terminal como forma de interacción. 

- **Graphic User Interface** son programas con ventanas y botones, que manejamos en dia a dia. 
- **Terminal** permite interactuar con la computadora mediante comandos del teclado, desde instrucciones a pulsasiones de teclas. 
    - **Shell** es 
        - **Kernel** es el 
            - **Host** es la maquina en si, los procesadores que interpretan codigo binario, bits de memoria, etc. 

**Porque la terminal es cool?**

- Acceso programatico, aka. que scripts y programas pueden acceder a la terminal para hacer trabajo.
- Ejecutar acciones complejas, como configurar multiples clusters desde un unico `.config`
- La mayor parte de los programas tiene un CLI pero no necesariamente un GUI, especialmente programas nicho como los usados en Ciencia. 
    - Hadoop
    - Slurm
    - Cosas CERN --posiblemente muchas, Laftraru, etc. 
    - AWS-CLI

## Terminales más usadas

- [PowerShell]() en Windows
- [BASH]() _Bourne Again SHell_ en la mayor parte de los sistemas Linux
- [ZSH]()
- [FISH]() una shell para 1990'

<!-- TODO: completar shells -->

# Instalando lineas de comandos POSIX en Windows

## Gestor de paquetes en Windows

A diferencia de la mayor parte de los sistemas Linux, Windows no trae nativamente un gestor de paquetes, aka. _una utilidad encargada de instalar programas desde un repositorio central_, como **apt** o **CRAN**.

Existen alternativas de terceros, como [Chocolatey](https:/www.chocolatey.org/), que nos permiten instalar programas via comandos. 

**Consideraciones**

- Esto requiere una terminal Powershell en modo administrador (porque estará instalando programas) 
- Requiere internet (para acceso al repo de programas)
- Requerimientos adicionales aplican a WSL2  

Para instalar Chocolatey, se usa la linea de comandos de Powershell de Windows

```powershell
Set-ExecutionPolicy Bypass -Scope Process -Force;
iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
```

La instalación dura unos pocos segundos, y luego se puede convocar a Chocolatey con el comando `choco`. 
Una lista de comandos se puede convocar con `choco help`

<details>
<summary>**Más comandos de Chocolatey**</summary>

- `choco install <paquete1> <paquete2>`  permite instalar multiples paquetes en un comando. `--yes` sirve para omitir las confirmaciones. Por ejemplo `choco install 7zip chrome -y`
- `choco search <paquete>` busca un programa en el repositorio central. Por ejemplo, `choco search cytoscape`
- `choco list --local` lista los paquetes instalados con Chocolatey. `choco list` lista todos los disponibles en el repositorio central (+1,300)
- `choco upgrade all` actualiza todos los paquetes actualizables. Recomiendo usar `--yes`
- `choco uninstall <paquete>` permite remover cosas

</details>

## Instalando WSL2 en Windows

Las ultimas versiones de Windows incluyen un Kernel Linux que corre de forma paralela al Kernel Windows NT propio de Windows. 
Este se denomina [_Windows Subsystem for Linux_](https://docs.microsoft.com/en-us/windows/wsl/install-win10), y es capaz de correr aplicaciones para Linux, hasta sistemas operativos como Ubuntu o Mint. 

WSL2 es la segunda versión mayor de este, con compatibilidad y rendimiento mejorados.

**Consideraciones**

- Requiere Windows posterior a 1903, ie. la versión de Marzo 2019

Para instalar WSL2, lo más facil es usando Chocolatey desde la consola en modo administrador (como la que usamos para instalarlo). 
Despues de completar la instalación, es necesario reiniciar la computadora para que pueda iniciar el Kernel Linux. 

```powershell
# Instalación de WSL2
choco install wsl2 -y

# Reboot del sistema
Restart-Computer
```

## Instalando Ubuntu como subsitema en Windows

La opción más efectiva es desde la [Tienda de Windows](https://www.microsoft.com/store/productId/9N6SVWS3RX71). 
Tambien es posible usar Chocolatey, pero por limitaciones de interoperabilidad de **WSL2**, choco no puede usarlo directamente y se ve limitado a usar **WSL1**. 

Luego, es posible acceder a la consola de Ubuntu con el comando `ubuntu2004`. Por defecto, esta incluye _bash_, _ssh_, _git_, etc. 

Este primer inicio es más lento que los siguientes, dado que el sistema instalara Ubuntu sobre el kernel, y ademas pedira la creación de un usuario para el sistema. 

```powershell
ubuntu2004
```
```
Installing, this may take a few minutes...
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username: USUARIO
New password:
Retype new password:
passwd: password updated successfully
Installation successful!

To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

Welcome to Ubuntu 20.04.1 LTS (GNU/Linux 4.4.0-19041-Microsoft x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Tue Nov 10 14:28:55 -03 2020
```

Para salir de este ambiente Ubuntu, usamos `logout` como en una sesión SSH.

### Otros ambientes Linux para WSL2

- [Debian](https://www.microsoft.com/store/productId/9MSVKQC78PK6)
- [OpenSUSE](https://www.microsoft.com/store/productId/9MZD0N9Z4M4H)
- [Alpine](https://www.microsoft.com/en-us/p/alpine-wsl/9p804crf0395?activetab=pivot:overviewtab) - No oficial (aunque toma una imagen oficial)

# Comandos básicos

La mayor parte de estos comandos existen tanto en Linux como en Windows Powershell (aunque en este ultimo realmente son alias). 
La principal diferencia es como las shells manejan directorios, con `/` en POSIX y `\` en Windows; 
y como manejan comandos multilinea, `\` y `` ` `` respectivamente. 

La parte más compleja y menos interoperable es cuando usamos comandos con `-parametros`.

## Navegación del sistema

- `cd` es _Change Directory_, mapea _Set-Directory_ en Powershell. 
    - `cd /un/path/especifico` cambia a un directorio segun un path directo o relativo  
    - `cd $VAR` dirige a un directorio definido por una variable ambiental, como `$HOME`  
    - `cd ..` permite subir al directorio superior, como en `/home/directory` a `/home`  
    - `cd -` es para volver rapidamente al directorio anterior. Util si cambian rapidamente entre un sub-sub-subdirectorio  
    - **Los paths usan `\` en Windows. `/` no funciona**
    
- `ls` es _LiSt_, mapeado a _Get-ChilItem_ en Powershell. 
    - `ls -a` lista todos los objetos en el directorio, incluyendo ocultos
    - `ls -lh` genera una lista en formato lista, con permisos, dueños, grupos, tamaño, etc.
    - `ls -r1 | sort | uniq -c | sort -nr` permite listar rapidamente archivos duplicados (por nombre) en un directorio y subdirectorios
    - **Los parametros no funcionan en Get-ChildItem**
    
- `mkdir` es _MaKe DIRectory_, mapea a _New-Item_ en Powershell. 
    - En *nix podemos crear multiples directorios y subdirectorios como ``mkdir Directorio/{Sub1, Sub2, Sub3}``
    - En Powershell necesitamos una sintaxis explicita; ie. ``mkdir Directorio\Sub1, Directorio\Sub2, ...``
    
- `ln`,es _LiNk_, no existe un map directo en Powershell. 
    - `ln -s <target> <link>` permite crear un vinculo `-s`imbolico
    - `ln -sf <target> <link>` permite actualizar el vinculo simbolico
    - **Una opción en Windows es desempolvar la vieja CMD.exe, y usar `MKLINK`**
    - `MKLINK \D <link> <target>` señala un link de `\D`irectorios

## Descargando archivos 
<!-- TODO: @alejandro Crear un script de R que toma 3 datasets y hace una reducción dimensional -->
- `curl` es _C (see) URL_, mapeado a _Invoke-WebRequest_ en Powershell.
    - `curl <url> -o <archivo>` descarga una URL para guardarla en un archivo
    - `curl -O <url>` descarga la URL a un archvio con su nombre. Usualmente usamos esto

- `wget` es _Web GET_, mapeado a _Invoke-WebRequest_ en Powershell. Es el más facil de usar. 
    - `wget <url> <url2…>` descarga la URL a un archvio con su nombre
    - `wget -c <url>` permite continuar una descarga interrumpida

- `Invoke-WebRequest` requiere un output explicito. 
    - `Invoke-WebRequest <url> -OutFile <archivo>`
    - `Invoke-WebRequest <url> -Method Get -o <archivo>` funciona igual que Wget
    - `wget <url> -o <archivo>` es valido en Windows base

## Descomprimiendo archivos

- `tar`, no existe en Windows.
    - `… xf …` son parametros para _eXtract_ y _File_
    - `tar xf <tar.gz.bz2.xz>` desempaca un tar (comprimido) al directorio local
    - `tar xf <tar.gz.bz2.xz> -C <directorio>` desempaca el tar a un directorio especifico
    - Los tar por defecto no están comprimidos. Un tar.gz si lo está. 
    - `tar cf <nuevo.tar> <archivo1 directorio/*>` crea un archivo tar.
    - `tar cgf <nuevo.tar.gz> <archivo1 directorio/*>` crea un archivo tar comprimido.

- `unzip`, no existe en Windows.
    - `unzip <zip>` extrae los contenidos de un zip en el directorio actual
    - `unzip <zip> -d <directorio>` extrae el zip a una carpeta especifica 
    - `zip -r <nuevo.zip> <directorio>` comprime un directorio a un zip. 

- `Expand-Archive` es una utilidad de Windows que funciona como `unzip`
    - `Expand-Archive <zip> <directorio>` descomprime un zip en un directorio existente o nuevo
    - `Compress-Archive -Path <directorio\*> -DestinationPath <nuevo.zip>` crea un zip con los contenidos de _directorio_

- `7zip` tiene linea de comandos para Linux, Mac, Windows. 

## Explorando y renombrando archivos

- `cat` es _conCATenate_, mapeado a _Get-Content_ en Powershell.
    - `cat <archivo>` pasa los contenidos de _archivo_ a la terminal, mostrandolos
    - `cat <archivo1> <archivo2> > <nuevo>` reemplaza los contenidos de _nuevo_ por la concatenación de _archivo1_ y _archivo2_
    - `cat <achivo3> >> <nuevo>` concatena _archivo3_ a _nuevo_

- `head`, no existe en Windows.
    - `head <archivo>` muestra las 10 primeras lineas de _archivo_
    - `head -n <archivo>` muestra las _n_ primeras lineas de _archivo_
    - En Windows, `Get-Content <archivo> -TotalCount 10` tiene el mismo comportamiento

- `tail`, no existe en Windows.
    - `tail <archivo>` muestra las 10 ultimas lineas de _archivo_
    - `tail -n <archivo>` muestra las _n_ ultimas lineas de _archivo_
    - En Windows, `Get-Content <archivo> -Tail 10` tiene el mismo comportamiento

<!-- AQUI SE ROMPE COMPATIBILIDAD CON WINDOWS NATIVO -->  

### Ejemplo de GREP para archivos

GREP significa "global regular expression print", este comando es utilizado para realizar busqueda
de patrones en archivos de textos.
Estructura  y sintaxis del comando:
Por defecto el comando grep devolvera todas las lineas en la que la expresion regular hace match,
cabe destacar que, dentro del argumento de la expresion regular se pueden utilizar operadores.
- `grep`
    - `grep "expresion_regular" <archivo>`  
Opciones utiles:

-i	Ignora mayusculas/minusculas
-w	Patron de palabra completa 
-v	Inversion de grep, devuelve las lineas que no tienen match
-l	Devuelve el nombre de los archivos que contienen el match 
-c	Cuenta y devuelve el numero de match para el patrón entregado

Operadores de expresiones regulares mas utilizados:

"."	Matches any single character.	
"?"	El caracter subsecuente hace match como maximo 1 vez.
"*"	El caracter subsecuente hace match 0 o mas veces.	
"+"	El caracter subsecuente hace match 1 o mas veces.	
### Ejemplos
Por lo general querremos usar el comando grep en conjunto de otros comando utilizando pipes.
'cat <archivo.fasta> | grep -c "ATG"' esto abrira el archivo de secuencias o archivo de texto plano 
luego buscara el patron ATG o codon start , contara la frecuencia y retornara el numero de matches.


### Ejemplo de ForEach 
### Ejemplo de %CG

<!-- Talla interna cenedyn -->
Foreach es un comando de C shell, por lo que no lo podremos usar a menos de que instalemos csh
 "sudo apt install csh" y abrir la desde la terminal utilizando "CSH"
- `foreach n (lista de elementos)
    #comando1 $n <- para los n elementos de la lista
    #comando2 $n <- para los n elementos de la lista
    end `
Generar una matriz de las frecuencias de los nucleotidos  por posicion
'cat >> estructuramatriz
A
C
T
G
'
'foreach pos (1 2 3 4 5 6 7 8 9)
cut -c$pos <archivo > | grep "A" | wc -l >> temporal$pos.txt
cut -c$pos <archivo> | grep "C" | wc -l >> temporal$pos.txt 
cut -c$pos <archivo> | grep "T" | wc -l >> temporal$pos.txt 
cut -c$pos <archivo> | grep "G" | wc -l >> temporal$pos.txt 
end
'
'paste estructuramatriz temporal* > Matriz_ACTG.txt
rm temporal*.txt'
De una forma similar podremos estimar el porcentaje de GC existente en la o las secuencias.
'cat <archivo> | grep -c "C"'
'cat <archivo> | grep -c "G"'
'cat <archivo> | grep -c "T"'
'cat <archivo> | grep -c "A"' 
sumar total, G + C y calcular %.
### Ejemplo WC 
Word count es un comando que permite realizar diferentes conteos, incluyendo palabras y
saltos de lineas.

### Ejemplo de Sed

<!-- TODO: ejemplo en SED con la cosa nefasta de ~GERO~ GERArdo -->

### How to stop a procces (podria ser vital explicarlo)
si se ven en problemas CTRL+C, es la alternativa mas rapida para detener un proceso corriendo
## Editores
<!-- TODO: terminar los ejemplos de los editores -->
### Nano

Este es el editor más familiar, con un modo de edición similar a Notepad, Word, cualquier programa general de texto.

### Vi

Vi es cool si tienen que escribir codigo, y tiene un _paradigma_. 

## Manipulando computadoras remotas via SSH

_Secure SHell_ es un programa presente en Linux y Windows 
(activado por defecto en las ultimas versiones), 
que permite establecer conexion a un host remoto a travez de una linea encriptada. 

```bash
ssh demo@<DIRECCIÓN DE LA MAQUINA>
touch <NOMBRE>.txt
```

### Copiando archivos entre remotos y locales con SCP

- `scp` _Secure CoPy_ permite transferir archivos entre un computador remoto y un local. 
    - `scp <remoto>:<archivo-remoto> <archivo-local>` para copiar de un remoto a local
    - `scp <archivo-local> <remoto>:<archivo-remoto>` para copiar de un remoto a local
    - `scp -r <remoto>:<directorio-remoto> <local>` para copiar un directorio remoto a local

SCP funciona para transferencias pequeñas, como scripts (.Rmd, .py) o archivos de datos individuales. 
Para transferir cantidades más grandes de datos, podemos usar 

### Acceso a Leftraru - Servidor de Supercomputo de Beacuhef

[Guia](https://wiki.nlhpc.cl/Tutorial_de_acceso_a_Leftraru_via_SSH)

### Comportamientos extraños en Windows

TODO: como se hace para que añada credenciales al archivo de configuración?

### SACRIFICANDO UNA EC2 para que vean porque root es demasiado poderoso

En casi todo sistema, es mala idea correr comandos como administrador. 

```bash
sudo rm -fr ./
sudo rm -fr  /
```


# Extras! - Cosas utiles y git para el proximo taller

- [Windows Terminal](https://github.com/microsoft/terminal) es la nueva terminal de Windows, con soporte para pestañas, multiples ambientes, mejores visuales, etc. 
    - [Instalar desde la Tienda](https://www.microsoft.com/en-us/p/windows-terminal/9n0dx20hk701)
    - [Documentación](https://docs.microsoft.com/en-us/windows/terminal/) con ejemplos
    - `choco install microsoft-windows-terminal -y` instala la nueva terminal
- [TLDR](https://github.com/tldr-pages/tldr), _Too Long; Didn't Read_ es una colección de manuales y paginas de ayuda resumidas para varias utilidades de terminal.
    - [TLDR.ostera.io](https://tldr.ostera.io) tiene una versión accesible via web
    - `tldr apt-get` muestra un ejemplo y caso de uso de `apt-get`
    - `apt-get install tldr` instala TLDR

## Instalando git

### En Windows

```powershell
choco install git --yes
```

### En Linux

En la mayor parte de las distros ya viene preinstalado. 
Sino, se puede instalar siguiendo esta [guia](https://git-scm.com/download/linux). 

### Comprobando la instalación

```bash
git version # muestra la versión
```
```
git version 2.29.2.windows.1
```
